// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: webcrawler/service.proto

package webcrawler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrawlerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CrawlerRequest) Reset() {
	*x = CrawlerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webcrawler_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrawlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlerRequest) ProtoMessage() {}

func (x *CrawlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webcrawler_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlerRequest.ProtoReflect.Descriptor instead.
func (*CrawlerRequest) Descriptor() ([]byte, []int) {
	return file_webcrawler_service_proto_rawDescGZIP(), []int{0}
}

func (x *CrawlerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type BatchCrawlerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*CrawlerRequest `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *BatchCrawlerRequest) Reset() {
	*x = BatchCrawlerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webcrawler_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchCrawlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCrawlerRequest) ProtoMessage() {}

func (x *BatchCrawlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webcrawler_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCrawlerRequest.ProtoReflect.Descriptor instead.
func (*BatchCrawlerRequest) Descriptor() ([]byte, []int) {
	return file_webcrawler_service_proto_rawDescGZIP(), []int{1}
}

func (x *BatchCrawlerRequest) GetUrls() []*CrawlerRequest {
	if x != nil {
		return x.Urls
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webcrawler_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_webcrawler_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_webcrawler_service_proto_rawDescGZIP(), []int{2}
}

var File_webcrawler_service_proto protoreflect.FileDescriptor

var file_webcrawler_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x77, 0x65, 0x62, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x77, 0x65, 0x62, 0x63,
	0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x22, 0x22, 0x0a, 0x0e, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x45, 0x0a, 0x13, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2e, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x61,
	0x77, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x75, 0x72, 0x6c,
	0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x8d, 0x01, 0x0a, 0x11, 0x77,
	0x65, 0x62, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x36, 0x0a, 0x05, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x12, 0x1a, 0x2e, 0x77, 0x65, 0x62, 0x63,
	0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x72, 0x61, 0x77, 0x6c,
	0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x40, 0x0a, 0x0a, 0x43, 0x72, 0x61, 0x77,
	0x6c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1f, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x72, 0x61, 0x77,
	0x6c, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x72, 0x61,
	0x77, 0x6c, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x77,
	0x65, 0x62, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_webcrawler_service_proto_rawDescOnce sync.Once
	file_webcrawler_service_proto_rawDescData = file_webcrawler_service_proto_rawDesc
)

func file_webcrawler_service_proto_rawDescGZIP() []byte {
	file_webcrawler_service_proto_rawDescOnce.Do(func() {
		file_webcrawler_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_webcrawler_service_proto_rawDescData)
	})
	return file_webcrawler_service_proto_rawDescData
}

var file_webcrawler_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_webcrawler_service_proto_goTypes = []interface{}{
	(*CrawlerRequest)(nil),      // 0: webcrawler.CrawlerRequest
	(*BatchCrawlerRequest)(nil), // 1: webcrawler.BatchCrawlerRequest
	(*Empty)(nil),               // 2: webcrawler.Empty
}
var file_webcrawler_service_proto_depIdxs = []int32{
	0, // 0: webcrawler.BatchCrawlerRequest.urls:type_name -> webcrawler.CrawlerRequest
	0, // 1: webcrawler.webCrawlerService.Crawl:input_type -> webcrawler.CrawlerRequest
	1, // 2: webcrawler.webCrawlerService.CrawlBatch:input_type -> webcrawler.BatchCrawlerRequest
	2, // 3: webcrawler.webCrawlerService.Crawl:output_type -> webcrawler.Empty
	2, // 4: webcrawler.webCrawlerService.CrawlBatch:output_type -> webcrawler.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_webcrawler_service_proto_init() }
func file_webcrawler_service_proto_init() {
	if File_webcrawler_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_webcrawler_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrawlerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webcrawler_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchCrawlerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webcrawler_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_webcrawler_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webcrawler_service_proto_goTypes,
		DependencyIndexes: file_webcrawler_service_proto_depIdxs,
		MessageInfos:      file_webcrawler_service_proto_msgTypes,
	}.Build()
	File_webcrawler_service_proto = out.File
	file_webcrawler_service_proto_rawDesc = nil
	file_webcrawler_service_proto_goTypes = nil
	file_webcrawler_service_proto_depIdxs = nil
}
