FROM nginx:alpine

COPY testdata/mock-channel-hero-page.html /usr/share/nginx/html/index.html
COPY testdata/mock-inavalid-page.html /usr/share/nginx/html/invalid.html
COPY testdata/mock-channel-no-data-page.html /usr/share/nginx/html/no-data.html