// Code generated by mockery v2.10.4. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// channelRepositoryMock is an autogenerated mock type for the ChannelRepository type
type channelRepositoryMock struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, channel
func (_m *channelRepositoryMock) Save(ctx context.Context, channel Channel) error {
	ret := _m.Called(ctx, channel)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Channel) error); ok {
		r0 = rf(ctx, channel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}


// rokuWebCrawlerMock is an autogenerated mock type for the RokuWebCrawler type
type rokuWebCrawlerMock struct {
	mock.Mock
}

// CrawlChannel provides a mock function with given fields: ctx, url
func (_m *rokuWebCrawlerMock) CrawlChannel(ctx context.Context, url Url) (*Channel, error) {
	ret := _m.Called(ctx, url)

	var r0 *Channel
	if rf, ok := ret.Get(0).(func(context.Context, Url) *Channel); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Channel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, Url) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
