name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run docker compose
        run: docker-compose up -d --build

      - name: Validate composer.json and composer.lock
        run: make test-integration
