name: CI

on:
  push:
    branches: [ ci-setup ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run docker compose
        run: docker-compose up -d --build

      - name: Run integration and acceptance tests
        run: make test-integration-acceptance
